Update content_catalog.md
dnd-al-krk/zasady-opk pull request #49
Opened 2024-03-24 19:30 UTC by Gormer0

2024-03-24 19:43 UTC, matiusz requested changes

2024-03-24 19:43 UTC, matiusz commented on content_catalog.md
> +### [Down in Flames]
Jeśli nie ma linku to nie rób notacji [ ]

2024-03-24 19:43 UTC, matiusz commented on content_catalog.md
> +
Przydałby się komentarz skąd mamy tę przygodę skoro nie ma do niej linku

2024-04-12 19:20 UTC, Mixxer5 commented on content_catalog.md
> +
@Gormer0 zlituj się, polskie znaki daj

2024-04-12 19:20 UTC, Mixxer5 commented on content_catalog.md
> +
I dokończ zdanie

2024-04-12 20:35 UTC, matiusz approved these changes

2024-04-12 20:35 UTC, merged